/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YearbookRouteImport } from './routes/yearbook'
import { Route as WallRouteImport } from './routes/wall'
import { Route as TributeRouteImport } from './routes/tribute'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as IndexRouteImport } from './routes/index'

const YearbookRoute = YearbookRouteImport.update({
  id: '/yearbook',
  path: '/yearbook',
  getParentRoute: () => rootRouteImport,
} as any)
const WallRoute = WallRouteImport.update({
  id: '/wall',
  path: '/wall',
  getParentRoute: () => rootRouteImport,
} as any)
const TributeRoute = TributeRouteImport.update({
  id: '/tribute',
  path: '/tribute',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/letter': typeof LetterRoute
  '/memories': typeof MemoriesRoute
  '/tribute': typeof TributeRoute
  '/wall': typeof WallRoute
  '/yearbook': typeof YearbookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/letter': typeof LetterRoute
  '/memories': typeof MemoriesRoute
  '/tribute': typeof TributeRoute
  '/wall': typeof WallRoute
  '/yearbook': typeof YearbookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/letter': typeof LetterRoute
  '/memories': typeof MemoriesRoute
  '/tribute': typeof TributeRoute
  '/wall': typeof WallRoute
  '/yearbook': typeof YearbookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/letter' | '/memories' | '/tribute' | '/wall' | '/yearbook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/letter' | '/memories' | '/tribute' | '/wall' | '/yearbook'
  id:
    | '__root__'
    | '/'
    | '/letter'
    | '/memories'
    | '/tribute'
    | '/wall'
    | '/yearbook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LetterRoute: typeof LetterRoute
  MemoriesRoute: typeof MemoriesRoute
  TributeRoute: typeof TributeRoute
  WallRoute: typeof WallRoute
  YearbookRoute: typeof YearbookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yearbook': {
      id: '/yearbook'
      path: '/yearbook'
      fullPath: '/yearbook'
      preLoaderRoute: typeof YearbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wall': {
      id: '/wall'
      path: '/wall'
      fullPath: '/wall'
      preLoaderRoute: typeof WallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tribute': {
      id: '/tribute'
      path: '/tribute'
      fullPath: '/tribute'
      preLoaderRoute: typeof TributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LetterRoute: LetterRoute,
  MemoriesRoute: MemoriesRoute,
  TributeRoute: TributeRoute,
  WallRoute: WallRoute,
  YearbookRoute: YearbookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
